### ISSUE TITLE
Mise à jour du rapport

### ISSUE THREAD

**Issue by NathanLiccardo** [RobinPetit/Projet-INFO-H-303#8]
Il faut également que l'on mette à jour le rapport afin d'avoir le projet finalisé. Pour le rapport de la partie 2 il faut : 
- [x] Mettre à jour en fonction des remarques de l'assistant ;
- [x] Les scripts SQL demandés dans l'énoncé ;
- [x] Les requêtes en algèbre relationnel et calcul relationnel tuple ;
- [x] Les instructions d'installation du programme ;
- [x] Un scénario d'utilisation du programme ;
- [x] Les justifications des choix et des hypothèses.

**Comment by RobinPetit** [comment]
Bon le tout est remis et le rapport est fini, je ferme.
